#!/bin/bash

return_code=0
if [[ -n "${BROWSER_DRIVER_INSTALLER_CHROME_VERSION:-}" && -n "${BROWSER_DRIVER_INSTALLER_CHROMEDRIVER_PATH:-}" ]]; then
    node ./index.js --browser-name Chrome                                        \
                    --browser-version "$BROWSER_DRIVER_INSTALLER_CHROME_VERSION" \
                    --target-path "$BROWSER_DRIVER_INSTALLER_CHROMEDRIVER_PATH" || return_code=$?
else 
    echo "The environment variables for Chrome are not set, skipping post-install for Chrome"
fi

if [[ -n "${BROWSER_DRIVER_INSTALLER_FIREFOX_VERSION:-}" && -n "${BROWSER_DRIVER_INSTALLER_GECKODRIVER_PATH:-}" ]]; then
    node ./index.js --browser-name Firefox                                        \
                    --browser-version "$BROWSER_DRIVER_INSTALLER_FIREFOX_VERSION" \
                    --target-path "$BROWSER_DRIVER_INSTALLER_GECKODRIVER_PATH" || return_code=$?
else 
    echo "The environment variables for Firefox are not set, skipping post-install for Firefox"
fi

exit $return_code